### ISSUE TITLE
Unable to resolve module "crypto"

### ISSUE THREAD

**Issue by 39otrebla** [mvayngrib/react-native-randombytes#10]
Hello there. Seems that the **sync** func requires SJCL, which depends on crypto.
"Crypto" module resolution fails, even having react-native-crypto installed and imported (through rn-nodeify's shim).

Ideas?

**UPDATE**:  I have been able to get rid of the "Cannot find module Crypto" error by requiring react-native-crypto directly [here](https://github.com/bitwiseshiftleft/sjcl/blob/master/sjcl.js#L50) (in node_modules, very odd I know). Then I got "Cannot find module vm", solved by installing and shimming browserify-vm via rn-nodeify. **But now....** I am getting a really wired "Can't find variable Buffer", and I am not able to debug where this happen because the app crashes with no further information.

Have you ever been able to successfully run this library?

react@15.4.2
react-native@0.42.0
node @ v6.9.5
npm @ 4.3.0

**UPDATE (2)**: I did try with react-native@0.35 (and react@15.3.2) and it works fine. Therefore it might be that new RN releases have broken this module, and I wouldn't be surprised since they have made a lot of changes on the packager in last releases (most of which have been included into the [0.40](https://github.com/facebook/react-native/releases/tag/v0.40.0) ).  Please let me know if you are going to continue the development of this, otherwise I will be forced to maintain my own fork.

P.S. at this point, I think would be better to move this issue to [rn-nodeify](https://github.com/mvayngrib/rn-nodeify), I think the problem comes from there.

**Comment by DarkHollow** [comment]
@39otrebla Have you managed to solve this?

I have needed to upgrade a project to react native 0.43.4 with same result as you, and at the point I don't know how to solve it.

**Comment by mvayngrib** [comment]
sorry guys for the unresponsiveness. I haven't gotten around to testing/upgrading this and rn-nodeify for react native >= 0.40, and may not get a chance till June. Happy to accept PRs.

**Comment by DarkHollow** [comment]
Don't worry. My problem actually was not related with randombytes.

**Comment by 39otrebla** [comment]
@DarkHollow yeah I managed to get it working. It's an odd workaround, but... It also depends on what exact dependency is complaining about `crypto` module. In my case it was `bip39`.

So [here](https://github.com/39otrebla/react-native-bip39) is what I did, look at the imported modules in `index.js`.

Let me know, I am glad to help. @mvayngrib no problem for not having updated rn-nodeify for >= 0.40, I might have some time for proposing a PR before June. If not, I will just wait for your precious work (btw, thank you for this library)

**Comment by DarkHollow** [comment]
Thank you @39otrebla !

**Comment by mikaoelitiana** [comment]
Hello. We are having the same issue, is there a recommended solution for this?

**Comment by mvayngrib** [comment]
@DarkHollow @39otrebla @mikaoelitiana see [rnctest1](https://github.com/mvayngrib/rnctest1) for a working example. Install the latest rn-nodeify from github as there have been a few updates.

**Comment by pcowgill** [comment]
Would it make sense to close this issue @DarkHollow @39otrebla @mikaoelitiana ?

**Comment by 39otrebla** [comment]
@pcowgill "green light" (for me). thanks.

**Comment by DarkHollow** [comment]
Yep, thank you!
