### ISSUE TITLE
Build tools version override?

### ISSUE THREAD

**Issue by MattFoley** [mvayngrib/react-native-randombytes#12]
I'm running into a bit of trouble with integrating this into my existing project on Android.

When running this through my CI, I end up with this output.

```
A problem occurred configuring project ':randombytes'.
> The SDK Build Tools revision (23.0.1) is too low for project ':randombytes'. Minimum required is 25.0.0
```

Our project is using buildtools "25.0.2" and compileSdkVersion "25", and I've forked/replaced these values in react-native-randombytes and pointed to my fork in my package.json. However, it seems that during the CI process, rn-nodeify is installing the version it wants over top of the branched version I have.

Is there any way to either a) Override the build tools so that I can use whichever version I want. or b) Stop rn-nodeify from overriding the version of random bytes I'd like to use. c) Upgrade the build.gradle file here to 25/25.0.2?

Thanks for your help!

**Comment by MattFoley** [comment]
Turns out that I was able to work around this by only calling --hack instead of --install during my CI process. (It'd be nice to know the answers to the other questions about upgrading/overriding, but feel free to close this issue)

**Comment by mvayngrib** [comment]
@MattFoley glad you got it working. You're right to raise the issue, a switch to prevent overwriting existing deps would be a good addition to rn-nodeify, something like --keep-existing or --no-overwrite, idk what's the convention. Happy to accept a PR if you want to add it.

**Comment by mvayngrib** [comment]
@MattFoley rn-nodeify no longer overwrites deps unless --overwrite is specified

**Comment by MattFoley** [comment]
Nice work
