### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olfek** [mvayngrib/react-native-randombytes#30]
undefined is not an object (evaluating 'RNRandomBytes.randomBytes')
I have run the `link` command

**Comment by olfek** [comment]
I can't check anymore as resorted to using Isaac (https://github.com/rubycon/isaac.js)
I got the error on Android if you were wondering.

**Comment by mvayngrib** [comment]
@olfek no problem. If you take your project into production and need a more secure source of randomness, this library uses the native OS's rng and falls back to [sjcl](https://github.com/bitwiseshiftleft/sjcl)
