### ISSUE TITLE
react-native run-android fails because of this package

### ISSUE THREAD

**Issue by rulatir** [mvayngrib/react-native-randombytes#4]
I did everything exactly as in README.md. I am getting this:

```
$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module randombytes : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Tried to run with the suggested debug flags, no further info obtained.

Googled for the error message, and it is apparently related to a missing build.gradle file. I do not find such a file anywhere in `node_modules/react-native-randombytes`. Also, I notice that the required modifications to gradle.settings refer to this path:

```
'../node_modules/react-native-randombytes/app'
```

The `app` subdir is also not present in `node_modules/react-native-randombytes` after installing the package with npm.

How can I solve this problem?

**Comment by mvayngrib** [comment]
@rulatir thanks for submitting the issue. I'm unfamiliar with the Android side of things, @arik-so @trave7er can you guys help with this one?

**Comment by rulatir** [comment]
Meanwhile could we figure out what **should** the contents of `node_modules/react-native-randombytes` look like? I might misunderstand how it works but it appears that substantial parts of code are just missing from there. For instance there is no /app subdir at all. In the repo the /app subdir contains the java (i.e. Android) code of the native module, and it would appear that perhaps someone forgot to include it in the package?

**Comment by mvayngrib** [comment]
@rulatir hm, i just tried installing react-native-randombytes in a new project and i see both the /app subdirectory and the build.gradle file. Maybe it's something on your end? Maybe you're installing version 1.x.x?

**Comment by rulatir** [comment]
Ah-HAH! It turns out that rn-nodeify --install downgrades both react-native-crypto and react-native-randombytes to 1.x.x. Should I file an issue for rn-nodeify?

**Comment by mvayngrib** [comment]
ah yea, i've been meaning to upgrade the dep in rn-nodeify. Yes, open an issue there
